// Certifications offered by PMI Services — values stored as serviceDescription.
export const CERTIFICATIONS = [
  'PgMP® – Program Management Professional',
  'MPM® – Master Project Manager',
  'CSM® – Certified Scrum Master',
  'PMP® – Project Management Professional',
  'CFM® – Certified in Financial Management',
  'CCIFP® – Certified Construction Industry Financial Professional',
  'CMA® – Certified Management Accountant',
  'IABA® – International Accredited Business Accountant',
  'QCI® – Quality Control Inspector Certification',
  'CQA® – Certified Quality Auditor',
  'MQM® – Master Quality Manager',
  'OSHA – Occupational Safety and Health Administration (OSHA) Safety Certificate',
  'COM® – Certified Operations Manager',
  'CPIM® – Certified in Production and Inventory Management',
  'CSCP® – Certified Supply Chain Professional',
  'ERP® – Enterprise Resource Planning Implementation Certification',
  'BPM® – Business Process Management Certification',
  'EIT® – Engineer in Training',
  'CAD® – Certified Agile Developer',
  'CME® – Certified Maintenance Engineer',
  'CMT® – Certified Maintenance Technician',
  'LSSGB® – Lean Six Sigma Green Belt',
  'ACP® – AutoCAD Certified Professional',
  'CCM® – Certified Construction Manager',
  'CCP® – Certified Construction Professional',
  'LEED AP BD+C® – LEED Accredited Professional: Building Design + Construction',
  'CSP® – Certified Safety Professional',
  'ISMC® – Industrial Safety Management Certification',
  'ISO 45001:2018 LA® – ISO 45001:2018 Occupational Health & Safety Lead Auditor Certification',
  'BESC® – Bridge Engineering & Structural Design Certification',
  'CDC® – Civil Design Certification',
  'CQSM® – Construction Quality & Safety Management Certification',
  'IPMC® – Infrastructure Project Management Certification',
  'CCFM® – Construction Contract & FIDIC Management Certification',
  'PPSC® – Project Planning & Scheduling Certification',
  'RMP® – Risk Management Professional',
  'SCMP® – Supply Chain Management Professional Certification',
  'PSSC® – Procurement & Strategic Sourcing Certification',
  'LSSBB® – Lean Six Sigma Black Belt',
  'DWOC® – Drilling & Well Operations Certification',
  'CSMC® – Commissioning & Start-up Management Certification',
  'IWCF® – International Well Control Forum Certification',
  'CSS® – Certified Site Supervisor',
  'PE® – Professional Engineer (Electrical)',
  'CEM® – Certified Energy Manager',
  'POMC® – Production & Operations Management Certification',
  'TPM® – Total Productive Maintenance Certification',
  'CME® – Certified Mechanical Engineer',
  'PE® – Professional Engineer (Mechanical)',
  'MMTC® – Mechanical Maintenance & Troubleshooting Certification',
  'PPM® – Preventive & Predictive Maintenance (TPM) Certification',
  'HPSC® – Hydraulic & Pneumatic Systems Certification',
  'CEP® – Certified Estimating Professional',
  'SPHR® – Senior Professional in Human Resources',
  'HRBP® – Human Resources Business Professional',
  'CCP® – Certified Compensation Professional',
  'PSEC® – Power System Engineering Certification',
  'EPSC® – Electrical Protection & Switchgear Certification',
  'IESC® – Industrial Electrical Safety Certification',
  'CSP® – Certified Sales Professional',
  'CSE® – Certified Sales Executive',
  'PCM® – Professional Certified Marketer',
  'CM® – Certified Manager',
  'TQM® – Total Quality Management Certification',
  'FMVC® – Financial Modeling & Valuation Certification',
  'BRDAC® – Business Research & Data Analytics Certification',
  'AEPB® – Advanced Excel & Power BI Certification',
  'CRS+AF® – Certified Resume Specialist: Accounting and Finance',
  'CPM® – Certified Purchasing Manager',
  'CPP® – Certified Purchasing Professional',
  'CPP® – Certified Process Professional',
  'ISO 9001:2015 LA® – ISO 9001:2015 Lead Auditor Certification',
  'FRM® – Financial Risk Manager',
  'ERM® – Enterprise Risk Management Certification',
  'CRMC® – Credit Risk Management Certification',
  'PRM® – Professional Risk Manager',
  'CPSM® – Certified Professional in Supply Management',
  'Ind AS® – Indian Accounting Standards Certification',
  'GST® – GST & Indirect Taxation Certification',
  'ITTP® – International Taxation & Transfer Pricing Certification',
  'CPA® – Certified Public Accountant',
  'CBDE® – Certified Business Development Expert',
  'CSSP® – Certified Strategic Sales Professional',
  'CCMC® – Commercial & Contract Management Certification',
  'SCPM® – Supply Chain & Procurement Management Certification',
  'FIDIC® – FIDIC Contract Management Certification',
  'CSM® – Certified Store Manager',
  'CICS® – Certified Inventory Control Supervisor',
  'CPS® – Certified Professional Supervisor',
  'CAP® – Certified Automation Professional',
  'ICTC® – Instrumentation & Control Technician Certification',
  'PLC® – PLC Programming Certification',
  'OMC® – Operations Management Certification',
  'SBDC® – Sales & Business Development Certification',
  'CLTD® – Certified in Logistics, Transportation and Distribution',
  'CMEP® – Certified MEP Engineer',
  'PE® – Professional Engineer (MEP)',
  'LEED AP® – LEED Accredited Professional',
  'PMC® – Payroll Management Certification',
  'LLSC® – Labour Laws & Statutory Compliance Certification',
  'TSSC® – Technical Sales & Solution Consulting Certification',
  'CRM® – Customer Relationship Management Certification',
  'SEPM® – Sales Engineering & Proposal Management Certification',
  'API® – Piping Inspector Certification',
  'CPM® – Certified Product Manager',
  'CSPO® – Certified Scrum Product Owner',
  'QSCM® – Quantity Surveying & Cost Management Certification',
  'CCE® – Certified Cost Engineer',
  'WIMC® – Warehouse & Inventory Management Certification',
  'LTMC® – Logistics & Transportation Management Certification',
  'ITIL® 4 / SOC® – Service Management (ITIL® 4 / Service Operations) Certification',
  'CCSP® – Certified Customer Service Professional',
  'CAM® – Certified Administrative Manager',
  'CAP® – Certified Administrative Professional',
  'CAPM® – Certified Administrative Professional Manager',
  'FMP® – Facility Management Professional',
  'ETAP® – ETAP Power System Analysis Certification',
  'MMP® – Maintenance Management Professional',
  'ELSM® – Executive Leadership & Strategic Management Certification',
  'ITIL® 4 MP – ITIL® 4 Managing Professional',
  'PfMP® – Portfolio Management Professional',
  'CMRP® – Certified Maintenance & Reliability Professional',
  'SME CMSP® – Society for Mining, Metallurgy & Exploration – Certified Mine Safety Professional',
  'QP® – Qualified Person (Mining & Mineral Resources) Certification',
  'CLA® – Certified Logistics Associate',
  'CLP® – Certified Logistics Professional',
  'CEE® – Certified Electrical Engineer',
  'ISO 55001® – Asset Management System Certification',
  'CFCC® – Certified FIDIC Contract Consultant',
  'CCM® – Certified Commercial Contracts Manager',
  'CFM® – Certified Facility Manager',
  'PMI-RMP® – Risk Management Professional',
  'POM® – Production & Operations Management Certification',
  'CIA® – Certified Internal Auditor',
  'CFE® – Certified Fraud Examiner',
  'CDC® – Certified Document Controller',
  'ISO 9001 QMS® – ISO 9001: Quality Management Systems – Documentation & Control Certification',
  'ACP® – Autodesk Certified Professional (Revit)',
  'BIM® – Building Information Modeling Certification',
  'CDCP® – Certified Digital Construction Professional',
  'CPP® – Certified Procurement Professional',
  'CCE/A® – Certified Cost Estimator/Analyst',
] as const;
